module.exports = Object.freeze({
    SIGNUP_SUCCESS_MSG: 'Successfully signed up',
    ROUND: 10,
    GET_MSG_BY_ID: 'User found by id',
    GET_MSG: 'Found record',
    ERROR_MSG: 'Something went wrong',
    LOGIN_SUCCESS_MSG: 'Successfully Logged in',
    EMAIL_LOGIN_ERR: 'Email is not exist',
    LOGIN_PASS_FAIL: 'Login fail',
    SUCCESS_LOGIN: 'User Logged in',
    ERROR_MSG: 'Email is not match',
    USER_LISTING_SUCCESS_MSG: 'User record found',
    ADD_TEAM_SUCCESS: 'Successfully added member',
    FOUND_TEAM_MEMBER: 'Found team member',
    PRODUCT_CREATE_SUCCESS_MSG: 'Product created successfully',
    PRODUCT_LISTING_SUCCESS: 'Found all product list',
    PRODUCT_TRUNCATE_MSG: 'product truncated',
    IMAGE_UPLOAD_SUCCESS: 'Image uploaded successfully',
    IMAGE_UPLOAD_ERR: 'Only Image format allowed!',
    TEAM_ADD_SUCCESS: 'Team member added',
    TRUNCATE_SUCCESS_MSG: 'Truncated'
})